routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// use App\Http\Controllers\HomeController;
// use App\Http\Controllers\Backend\RoleController;
// use App\Http\Controllers\Backend\UserController;
// use App\Http\Controllers\Backend\ProductController;
// use App\Http\Controllers\Backend\IndexController;
// use App\Http\Controllers\Backend\CategoryController;
// use App\Http\Controllers\Backend\GlobalSettingsController;
// use App\Http\Controllers\Backend\VendorCategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
 
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth'], 'prefix' => 'system'], function() {
    // Route::get('system/dashboard', 'IndexController@index')->name('system.home');
    Route::get('/dashboard', 'Backend\IndexController@index')->name('system.home');
    Route::resource('/roles', 'Backend\RoleController');
    Route::resource('/users', 'Backend\UserController');
    Route::resource('/products', 'Backend\ProductController');
    Route::resource('/categories', 'Backend\CategoryController');
    Route::resource('/global-settings', 'Backend\GlobalSettingsController');

    //// Vendor Category ////
    Route::resource('/vendor-category', 'Backend\VendorCategoryController',  [
        'names' => [
            'create' => 'system.vendor-category.create',
            'edit' => 'system.vendor-category.edit',
            'show' => 'system.vendor-category.show',
        ]])->only(['create', 'edit', 'show']);

    Route::match(['get', 'post'], '/vendor-category', 'Backend\VendorCategoryController@index')->name('system.vendor-category');
    Route::post('/vendor-category/store', 'Backend\VendorCategoryController@store')->name('system.vendor-category.store');
    Route::match(['get', 'post'], '/vendor-category/delete/{id}', 'Backend\VendorCategoryController@destroy')
        ->where(['id'=>'[0-9]+'])->name('system.vendor-category.delete');

    //// Vendor Tournament ////
    Route::match(['get', 'post'], '/vendor-tournament', 'Backend\VendorTournamentController@index')->name('vendor_tournament.index');
    Route::post('/vendor-tournament/store', 'Backend\VendorTournamentController@store')->name('vendor_tournament.store');
    Route::match(['get', 'post'], '/vendor-tournament/delete/{id}', 'Backend\VendorTournamentController@destroy')
        ->where(['id'=>'[0-9]+'])->name('vendor_tournament.destroy');
    Route::get('/vendor-tournament/{id}/edit', 'Backend\VendorTournamentController@edit')->name('vendor_tournament.edit');
    Route::post('/vendor-tournament/update', 'Backend\VendorTournamentController@update')->name('vendor_tournament.update');

    //// Vendor ////
    // Route::get('/vendor-category/{id}', 'Backend\VendorController@index');
    Route::resource('/vendor', 'Backend\VendorController',  [
        'names' => [
            'create' => 'system.vendor.create',
            'edit' => 'system.vendor.edit',
        ]])->only(['create', 'edit']);

    Route::get('/vendor/{cat_id?}', 'Backend\VendorController@index')->name('system.vendor');
    Route::post('/vendor/store', 'Backend\VendorController@store')->name('system.vendor.store');
    Route::match(['get', 'post'], '/vendor/delete/{id}', 'Backend\VendorController@destroy')
        ->where(['id'=>'[0-9]+'])->name('system.vendor.delete');

});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *	
     * @var array
     */
    protected $fillable = [
        'name', 'detail'
    ];
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;

class CategoryController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:category-list|category-create|category-edit|category-delete', ['only' => ['index','show']]);
        $this->middleware('permission:category-create', ['only' => ['create','store']]);
        $this->middleware('permission:category-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:category-delete', ['only' => ['destroy']]);
    }

    public function index()
    {
        $categories = Category::latest()->paginate(5);
        return view('backend.categories.index',compact('categories'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }
    
    public function create()
    {
        return view('backend.categories.create');
    }
    
    public function store(Request $request)
    {
        request()->validate([
            'title' => 'required',
            'description' => 'required',
        ]);
    
        Category::create($request->all());
    
        return redirect()->route('categories.index')
                        ->with('success','Category created successfully.');
    }
    
    public function show(Category $category)
    {
        return view('backend.categories.show',compact('category'));
    }

    public function edit(Category $category)
    {
        return view('backend.categories.edit',compact('category'));
    }
    
    public function update(Request $request, Category $category)
    {
        request()->validate([
            'title' => 'required',
            'description' => 'required',
        ]);
    
        $category->update($request->all());
    
        return redirect()->route('categories.index')
                        ->with('success','Category updated successfully');
    }
    
    public function destroy(Category $category)
    {
        $category->delete();
    
        return redirect()->route('categories.index')
                        ->with('success','Category deleted successfully');
    }
}

app/Http/Controllers/Backend/GlobalSettingsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class GlobalSettingsController extends Controller
{
    //
}

app/Http/Controllers/Backend/IndexController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class IndexController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        return view('backend.home');
    }
}

app/Http/Controllers/Backend/ProductController.php
<?php
    
namespace App\Http\Controllers\Backend;
    
use App\Models\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
    
class ProductController extends Controller
{ 
    function __construct()
    {
        $this->middleware('permission:product-list|product-create|product-edit|product-delete', ['only' => ['index','show']]);
        $this->middleware('permission:product-create', ['only' => ['create','store']]);
        $this->middleware('permission:product-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:product-delete', ['only' => ['destroy']]);
    }

    public function index()
    {
        $products = Product::latest()->paginate(5);
        return view('backend.products.index',compact('products'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }
    
    public function create()
    {
        return view('backend.products.create');
    }
    
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required',
            'detail' => 'required',
        ]);
    
        Product::create($request->all());
    
        return redirect()->route('products.index')
                        ->with('success','Product created successfully.');
    }
    
    public function show(Product $product)
    {
        return view('backend.products.show',compact('product'));
    }

    public function edit(Product $product)
    {
        return view('backend.products.edit',compact('product'));
    }
    
    public function update(Request $request, Product $product)
    {
         request()->validate([
            'name' => 'required',
            'detail' => 'required',
        ]);
    
        $product->update($request->all());
    
        return redirect()->route('products.index')
                        ->with('success','Product updated successfully');
    }
    
    public function destroy(Product $product)
    {
        $product->delete();
    
        return redirect()->route('products.index')
                        ->with('success','Product deleted successfully');
    }
}

app/Http/Controllers/Backend/RoleController.php
<?php
    
namespace App\Http\Controllers\Backend;


use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use DB;
    
class RoleController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:role-list|role-create|role-edit|role-delete', ['only' => ['index','store']]);
        $this->middleware('permission:role-create', ['only' => ['create','store']]);
        $this->middleware('permission:role-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:role-delete', ['only' => ['destroy']]);
    }
    
    public function index(Request $request)
    {
        $roles = Role::orderBy('id','DESC')->paginate(5);
        return view('backend.roles.index',compact('roles'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }
    
    public function create()
    {
        $permission = Permission::get();
        return view('backend.roles.create',compact('permission'));
    }
    
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles,name',
            'permission' => 'required',
        ]);
    
        $role = Role::create(['name' => $request->input('name')]);
        $role->syncPermissions($request->input('permission'));
    
        return redirect()->route('roles.index')
                        ->with('success','Role created successfully');
    }

    public function show($id)
    {
        $role = Role::find($id);
        $rolePermissions = Permission::join("role_has_permissions","role_has_permissions.permission_id","=","permissions.id")
            ->where("role_has_permissions.role_id",$id)
            ->get();
    
        return view('backend.roles.show',compact('role','rolePermissions'));
    }
    
    public function edit($id)
    {
        $role = Role::find($id);
        $permission = Permission::get();
        $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id",$id)
            ->pluck('role_has_permissions.permission_id','role_has_permissions.permission_id')
            ->all();
    
        return view('backend.roles.edit',compact('role','permission','rolePermissions'));
    }
    
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'permission' => 'required',
        ]);
    
        $role = Role::find($id);
        $role->name = $request->input('name');
        $role->save();
    
        $role->syncPermissions($request->input('permission'));
    
        return redirect()->route('roles.index')
                        ->with('success','Role updated successfully');
    }

    public function destroy($id)
    {
        DB::table("roles")->where('id',$id)->delete();
        return redirect()->route('roles.index')
                        ->with('success','Role deleted successfully');
    }
}

app/Http/Controllers/Backend/UserController.php
<?php
    
namespace App\Http\Controllers\Backend;
    
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;
use Spatie\Permission\Models\Role;
use DB;
use Hash;
use Illuminate\Support\Arr;
    
class UserController extends Controller
{
    public function index(Request $request)
    {
        $data = User::orderBy('id','DESC')->paginate(5);
        return view('backend.users.index',compact('data'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }
    
    public function create()
    {
        $roles = Role::pluck('name','name')->all();
        return view('backend.users.create',compact('roles'));
    }
    
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|same:confirm-password',
            'roles' => 'required'
        ]);
    
        $input = $request->all();
        $input['password'] = Hash::make($input['password']);
    
        $user = User::create($input);
        $user->assignRole($request->input('roles'));
    
        return redirect()->route('users.index')
                        ->with('success','User created successfully');
    }
    
    public function show($id)
    {
        $user = User::find($id);
        return view('backend.users.show',compact('user'));
    }
    
    public function edit($id)
    {
        $user = User::find($id);
        $roles = Role::pluck('name','name')->all();
        $userRole = $user->roles->pluck('name','name')->all();
    
        return view('backend.users.edit',compact('user','roles','userRole'));
    }
    
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email,'.$id,
            'password' => 'same:confirm-password',
            'roles' => 'required'
        ]);
    
        $input = $request->all();
        if(!empty($input['password'])){ 
            $input['password'] = Hash::make($input['password']);
        }else{
            $input = Arr::except($input,array('password'));    
        }
    
        $user = User::find($id);
        $user->update($input);
        DB::table('model_has_roles')->where('model_id',$id)->delete();
    
        $user->assignRole($request->input('roles'));
    
        return redirect()->route('users.index')
                        ->with('success','User updated successfully');
    }
    
    public function destroy($id)
    {
        User::find($id)->delete();
        return redirect()->route('users.index')
                        ->with('success','User deleted successfully');
    }
}

resources/views/backend/products/create.blade.php
@extends('backend.master')

@section('content')
<!-- Main content -->
<section class="container-fluid">
  <div class="card">

    <div class="card-header">
      <h2 class="card-title"> Add New </h2>
      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
          <i class="fas fa-minus"></i>
        </button>

        <button type="button" class="btn btn-tool">
          <a href="{{url('system/products')}}" class="btn btn-info btn-sm"><i class="mdi mdi-plus"></i> <i
              class="fa fa-arrow-left"></i> Back</a>
        </button>
      </div>
    </div>


    <form method="post" action="{{url('system/products')}}" enctype="multipart/form-data">
      @csrf

      <div class="card-body">

        @if ($errors->any())
        <div class="alert alert-danger">
          <strong>Whoops!</strong> There were some problems with your input.<br><br>
          <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
          </ul>
        </div>
        @endif

        <div class="form-group row" id="area_charge">
          <label class="col-sm-4 col-form-label" for="charge">Title</label>
          <div class="col-sm-8">
            <input name="name" id="name" type="text" class="form-control">
          </div>
        </div>

        <div class="form-group row">
          <label class="col-sm-4 col-form-label" for="detail">Details </label>
          <div class="col-sm-8">
            <textarea name="detail" id="detail" type="text" class="form-control"> </textarea>
          </div>
        </div>

      </div>

      <div class="card-footer">
        <div class="row">
          <div class="col-sm-6">
            <div class="form-group row">
              <div class="col-sm-4"></div>
              <div class="col-sm-8">
                <button type="submit" class="btn btn-primary">Save</button>&nbsp;&nbsp;
                <a href="{{url('system/products')}}" class="btn btn-warning">Cancel</a>
              </div>
            </div>
          </div>
        </div>
      </div>

    </form>

  </div>
</section>
<!-- /.content -->
@endsection

resources/views/backend/products/edit.blade.php
@extends('backend.master')

@section('content')
<!-- Main content -->
<section class="container-fluid">
  <div class="card">

    <div class="card-header">
      <h2 class="card-title"> Edit Product </h2>
      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
          <i class="fas fa-minus"></i>
        </button>

        <button type="button" class="btn btn-tool">
          <a href="{{url('system/products')}}" class="btn btn-info btn-sm"><i class="mdi mdi-plus"></i> <i
              class="fa fa-arrow-left"></i> Back</a>
        </button>
      </div>
    </div>


    <form method="post" action="{{ route('products.update',$product->id) }}" enctype="multipart/form-data">
      @method('put')
      @csrf

      <div class="card-body">

        @if ($errors->any())
        <div class="alert alert-danger">
          <strong>Whoops!</strong> There were some problems with your input.<br><br>
          <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
          </ul>
        </div>
        @endif




        <div class="form-group row" id="area_charge">
          <label class="col-sm-4 col-form-label" for="charge">Title</label>
          <div class="col-sm-8">
            <input name="name" id="name" type="text" class="form-control" value="{{ $product->name }}">
          </div>
        </div>

        <div class="form-group row">
          <label class="col-sm-4 col-form-label" for="detail">Details </label>
          <div class="col-sm-8">
            <textarea name="detail" id="detail" type="text" class="form-control"> {{ $product->detail }}</textarea>
          </div>
        </div>

      </div>

      <div class="card-footer">
        <div class="row">
          <div class="col-sm-6">
            <div class="form-group row">
              <div class="col-sm-4"></div>
              <div class="col-sm-8">
                <button type="submit" class="btn btn-primary">Update</button>&nbsp;&nbsp;
                <a href="{{url('system/products')}}" class="btn btn-warning">Cancel</a>
              </div>
            </div>
          </div>
        </div>
      </div>

    </form>

  </div>
</section>
<!-- /.content -->
@endsection

resources/views/backend/products/index.blade.php
@extends("backend.master")
@section("content")

<section class="content">
  <!-- Default box -->
  <div class="row">

    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h2 class="card-title"> Role List </h2>
          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>

            @can('product-create')
            <button type="button" class="btn btn-tool">
              <a href="{{url('system/products/create')}}" class="btn bg-gradient-info custom_btn"><i class="mdi mdi-plus"></i>
                <i class="fa fa-plus-circle"></i> Add New </a>
            </button>
            @endcan 

          </div>
        </div>
        <div class="card-body frontoffice-body">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th class="text-center" width="5%">SL</th>
                <th class="sort" data-row="name" id="name" width="20%">Title</th>
                <th width="20%">Details</th>
                <th class="text-center" width="20%">Manage</th>
              </tr>
            </thead>
            <tbody>
              @if ($products->count() > 0)

              @foreach ($products as $key => $product)
              <tr>
                <td class="text-center" width="5%">{{ ++$key }}</td>
                <td class="pl-1" width="20%">{{ $product->name }}</td>
                <td class="pl-1" width="20%">{{ $product->detail }}</td>

                <td class="text-center" width="20%">
                  <div class="btn-group">

                    <button type="button" class="btn btn-outline-info">
                      <a href="{{ route('products.show',$product->id) }}"><i class="fa fa-table"></i> </a>
                    </button>

                    <button type="button" class="btn btn-outline-info dropdown-toggle dropdown-hover dropdown-icon"
                      data-toggle="dropdown">
                    </button>
                    <div class="dropdown-menu" role="menu" style="">

                      @can('product-edit')
                      <a class="dropdown-item" href="{{ route('products.edit',$product->id) }}"><i
                          class="fa fa-edit"></i>
                        Edit</a>
                      @endcan

                      <div class="dropdown-divider"></div>
                      @can('product-delete')
                      <form action="{{ route('products.destroy',$product->id) }}" method="POST">
                        @csrf
                        @method('DELETE')

                        <button type="submit" class="btn btn-danger">Delete</button>
                      </form>
                      @endcan

                    </div>
                  </div>
                </td>
              </tr>

              @endforeach

              @else

              <tr>
                <td colspan="5">There is nothing found.</td>
              </tr>


              @endif
            </tbody>
          </table>
          <div class="row mt-4">

            <div class="col-md-9">
              <div class="pagination_table">
                {!! $products->links() !!}
              </div>
            </div>
          </div>
        </div>
        <div class="card-footer">

        </div>
      </div>

    </div>
  </div>
</section>

@endsection

resources/views/backend/products/show.blade.php
@extends("backend.master")
@section("content")
<!-- Main content -->
<section class="container-fluid">

  <div class="card">

    <div class="card-header">
      <h2 class="card-title"> Product Information </h2>
      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
          <i class="fas fa-minus"></i>
        </button>

        <button type="button" class="btn btn-tool">
          @can('product-edit')
            <a href="{{url('system/products/'.$product->id.'/edit')}}" class="btn btn-info btn-sm"><i class="mdi mdi-plus"></i>
            <i class="fa fa-edit"></i> Edit</a>
          @endcan 
          <a href="{{url('system/products')}}" class="btn btn-info btn-sm"><i class="mdi mdi-plus"></i> <i
              class="fa fa-arrow-left"></i> Back</a>
        </button>
      </div>
    </div>

    <div class="card-body">
      <div class="col-md-11">
        <div class="row">
          <label class="col-sm-3">Title</label>
          <div class="col-sm-9">
            {{ $product->name }}
          </div>
        </div>

        <div class="row">
          <label class="col-sm-3">Details</label>
          <div class="col-sm-9">
            {{ $product->detail }}
          </div>
        </div>

      </div>
    </div>
  </div>
  </div>
</section>
@endsection