routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// use App\Http\Controllers\HomeController;
// use App\Http\Controllers\Backend\RoleController;
// use App\Http\Controllers\Backend\UserController;
// use App\Http\Controllers\Backend\ProductController;
// use App\Http\Controllers\Backend\IndexController;
// use App\Http\Controllers\Backend\CategoryController;
// use App\Http\Controllers\Backend\GlobalSettingsController;
// use App\Http\Controllers\Backend\VendorCategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
 
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth'], 'prefix' => 'system'], function() {
    // Route::get('system/dashboard', 'IndexController@index')->name('system.home');
    Route::get('/dashboard', 'Backend\IndexController@index')->name('system.home');
    Route::resource('/roles', 'Backend\RoleController');
    Route::resource('/users', 'Backend\UserController');
    Route::resource('/products', 'Backend\ProductController');
    Route::resource('/categories', 'Backend\CategoryController');
    Route::resource('/global-settings', 'Backend\GlobalSettingsController');

    //// Vendor Category ////
    Route::resource('/vendor-category', 'Backend\VendorCategoryController',  [
        'names' => [
            'create' => 'system.vendor-category.create',
            'edit' => 'system.vendor-category.edit',
            'show' => 'system.vendor-category.show',
        ]])->only(['create', 'edit', 'show']);

    Route::match(['get', 'post'], '/vendor-category', 'Backend\VendorCategoryController@index')->name('system.vendor-category');
    Route::post('/vendor-category/store', 'Backend\VendorCategoryController@store')->name('system.vendor-category.store');
    Route::match(['get', 'post'], '/vendor-category/delete/{id}', 'Backend\VendorCategoryController@destroy')
        ->where(['id'=>'[0-9]+'])->name('system.vendor-category.delete');

    //// Vendor Tournament ////
    Route::match(['get', 'post'], '/vendor-tournament', 'Backend\VendorTournamentController@index')->name('vendor_tournament.index');
    Route::post('/vendor-tournament/store', 'Backend\VendorTournamentController@store')->name('vendor_tournament.store');
    Route::match(['get', 'post'], '/vendor-tournament/delete/{id}', 'Backend\VendorTournamentController@destroy')
        ->where(['id'=>'[0-9]+'])->name('vendor_tournament.destroy');
    Route::get('/vendor-tournament/{id}/edit', 'Backend\VendorTournamentController@edit')->name('vendor_tournament.edit');
    Route::post('/vendor-tournament/update', 'Backend\VendorTournamentController@update')->name('vendor_tournament.update');

    //// Vendor ////
    // Route::get('/vendor-category/{id}', 'Backend\VendorController@index');
    Route::resource('/vendor', 'Backend\VendorController',  [
        'names' => [
            'create' => 'system.vendor.create',
            'edit' => 'system.vendor.edit',
        ]])->only(['create', 'edit']);

    Route::get('/vendor/{cat_id?}', 'Backend\VendorController@index')->name('system.vendor');
    Route::post('/vendor/store', 'Backend\VendorController@store')->name('system.vendor.store');
    Route::match(['get', 'post'], '/vendor/delete/{id}', 'Backend\VendorController@destroy')
        ->where(['id'=>'[0-9]+'])->name('system.vendor.delete');

});

resources/views/layouts/app.blade.php
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Laravel 8 User Roles and Permissions Tutorial') }}</title>
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Laravel 8 User Roles and Permissions - ItSolutionStuff.com
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
    
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto"></ul>


                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li><a class="nav-link" href="{{ route('users.index') }}">Manage Users</a></li>
                            <li><a class="nav-link" href="{{ route('roles.index') }}">Manage Role</a></li>
                            <li><a class="nav-link" href="{{ route('products.index') }}">Manage Product</a></li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>


                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>


                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>


        <main class="py-4">
            <div class="container">
            @yield('content')
            </div>
        </main>
    </div>
</body>
</html>